# External gems
gems:
  - jekyll-sitemap

# Site settings
title: University of Alberta Aerial Robotics Group
subtitle: "UAARG"
email: uaarginfo@gmail.com
description: > 
  University of Alberta Aerial Robotics Group
baseurl: "/centrarium" # the subpath of your site, e.g. /blog/
url: "http://uaarg.com" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Disqus comments
disqus_shortname: uaarg

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
# - name: Twitter
#   icon: twitter
#   username: "@TheBenCentra"
#   url: https://twitter.com/TheBenCentra
#   desc: Follow me on Twitter
#   share_url: http://twitter.com/share
#   share_title: ?text=
#   share_link: "&amp;url="

  - name: Facebook
    icon: facebook
    username: uaarg
    url: 
    desc: Find us on Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - name: GitHub
    icon: github
    username: uaarg
    url: https://github.com/uaarg
    desc: GitHub
    share_url:
    share_title:
    share_link:

  - name: YouTube
    icon: youtube
    username: uaarg
    url: https://www.youtube.com/user/UAARG
    desc: Subscribe on YouTube
    share_url: 
    share_title: 
    share_link:


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
#protocols:
#    fb_image: "assets/logo.png"
#    fb_image_width: 612
#    fb_image_height: 605
#    fb_image_type: "image/png"
#
#    twitter_image: "assets/logo.png"
#
#    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
#    os_rcs_type: "git"
#    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
